apiVersion: v1
kind: Pod
metadata:
  name: simple-nginx
  namespace: dev
  labels:
    app: nginx
    environment: practice
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
      name: http