apiVersion: v1
kind: Pod
metadata:
  name: resource-quota
  namespace: dev
spec:
  containers:
    - name: app
      image: nginx:alpine
      resources: 
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits: 
          memory: "128Mi"