apiVersion: v1
kind: Service
metadata:
  name: svc-headless
  namespace: dev
spec:
  clusterIP: None
  selector:
    app: busybox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      