apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-dep
  namespace: dev
  labels:
    type: hap 
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hpa
  template:
    metadata:
      labels:
        app: hpa
    spec:
      containers:
        - name: hpa
          image: nginx:1.14.2
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 150Mi
            requests:
              cpu: 64m
              memory: 128Mi
        - name: stress
          image: busybox
          command: ["/bin/sh"]
          args: ["-c", "while true; do dd if=/dev/zero of=/dev/null bs=1M count=1; sleep 1; done"]
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 30m
              memory: 30Mi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-dep
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 2
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-svc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: hpa
  ports:
  -  port: 80
     targetPort: 80
     protocol: TCP