apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo-dev
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: stclass-demodev
  resources:
    requests:
      storage: 1Gi

    
  
  

