apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: dev
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        -  containerPort: 8081
        env:
        -  name: ME_CONFIG_MONGODB_ADMINUSERNAME
           valueFrom:
             secretKeyRef:
               name: mongo-mysecret
               key: mongodb-root-username
        -  name: ME_CONFIG_MONGODB_ADMINPASSWORD
           valueFrom:
             secretKeyRef:
               name: mongo-mysecret
               key: mongodb-root-password
        -  name: ME_CONFIG_MONGODB_SERVER
           valueFrom:
            configMapKeyRef:
              name: demo-configmap
              key: db_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-svc
  namespace: dev
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30000