apiVersion: v1
kind: Pod
metadata:
  name: antinode-affinity
  namespace: dev
spec:
  containers:
  -  name: pod-antinodeaffinity
     image: nginx
     ports:
     - containerPort: 80
     resources:
       requests:
         cpu: 64m
         memory: 128Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: NotIn
            values:
            - ssd       