apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
  namespace: dev
spec:
  containers:
  -  name: pod-nodeaffinity
     image: nginx
     ports:
     - containerPort: 80
     resources:
       requests:
         cpu: 64m
         memory: 128Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd       