apiVersion: v1
kind: Pod
metadata:
  name: pod-probe
  namespace: dev
  labels:
    app: probe
spec:
  containers:
    - name: probe
      image: registry.k8s.io/busybox:1.27.2
      resources:
        requests: 
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
