apiVersion: v1
kind: Pod
metadata:
  name: pod-antiaffinity
  namespace: dev
spec:
  containers:
  - name: podantiaffinity
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 32m
        memory: 128Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
              -  be
        topologyKey: kubernetes.io/hostname