apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
  namespace: dev
spec:
  containers:
  - name: podeaffinity
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 32m
        memory: 128Mi
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
              -  fe
        topologyKey: kubernetes.io/hostname